[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "crm"
authors = [{name = "Mukopaje", email = "mukopaje@gmail.com"}]
dynamic = ["version", "description"]
